version: '3'
services:

  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    stdin_open: true
    env_file:
      - .env
    ports: 
      - "3000:3000"
    stdin_open: true

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"

